version: "3.8"

services:

  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092:9092"
    networks:
      - backend_service
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

  console:
    image: redpandadata/console:latest
    environment:
      - KAFKA_BROKERS=kafka:9092
    ports:
      - "8082:8080"
    networks:
      - backend_service
    depends_on:
      - kafka

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8081:8080"
    networks:
      - backend_service
    volumes:
      - ./wiremock:/home/wiremock

networks:
  backend_service:
    driver: bridge

volumes:
  kafka_data:
    driver: local